# Generated by Django 3.0.5 on 2020-05-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaries',
            name='id',
        ),
        migrations.AlterField(
            model_name='dictionaries',
            name='spell',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
