# Generated by Django 3.0.5 on 2020-05-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200511_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaries',
            name='chinese',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dictionaries',
            name='eggs',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dictionaries',
            name='spell',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dictionaries',
            name='tp',
            field=models.CharField(max_length=50),
        ),
    ]
