# Generated by Django 3.0.5 on 2020-05-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200511_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaries',
            name='eggs',
        ),
    ]
